### PR TITLE
feat/#116: load imprint from file

### LINKED ISSUE #116: load imprint and AGB from textfile
styled via html or markdown - check options.

### PR DESCRIPTION
**Pull request by kindOfCurly**
- installed react-markdown
- added md file for imprint and conditions of use (lipsum)
- used ReactMarkdown-tag to display imprint

closes #116

### CODE REVIEW

**Comment by kindOfCurly** [comment]
Actually you get an error because of nested <p>. This is because the <Typography> is rendered to <p> and the <ReactMarkdown> is also rendered to <p>.
Still I found it more useful to use <Typography> for styling.

Would like to hear your opinion.

**Review by cetceeve — APPROVED** [review]
Love it. Much less of ugly html 😌

**Comment by cetceeve** [comment]
> Actually you get an error because of nested
> 
> . This is because the is rendered to
> 
> and the is also rendered to
> 
> .
> Still I found it more useful to use for styling.
> 
> Would like to hear your opinion.

I dont realy understand?
What kind of nested error?

**Comment by kindOfCurly** [comment]
> 
> 
> > Actually you get an error because of nested
> > . This is because the is rendered to
> > and the is also rendered to
> > .
> > Still I found it more useful to use for styling.
> > Would like to hear your opinion.
> 
> I dont realy understand?
> What kind of nested error?

Sorry. Writign of html-tags in markdown isn't a good idea!
So: typography-tag is rendered as p-tag. And reactmarkdown-tag ist also rendered as p-tag.
This makes nested p-tags which gives a warning.

**Comment by cetceeve** [comment]
Assigning the `<Typography />` tag to another different component, maybe `<div>` could solve this issue.
See [Typography API](https://material-ui.com/api/typography/#typography-api): `component` attribute.

**Review by cetceeve — APPROVED** [review]

**Pull request merged**
